version: '3.4'

services:
  dockercrud:
    image: ${DOCKER_REGISTRY-}dockercrud
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
       - "8080:8081"

  sqldata:        
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
       - MSSQL_SA_PASSWORD=abD5r9tn0M@4
       - ACCEPT_EULA=Y
    ports: 
       - "1450:1433"

  